name: libyang CI
on:
  workflow_dispatch:

jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        GREETING: Hi, My name is 
        FULL_NAME: Dycloud
      run: |
        echo $GREETING $FULL_NAME.
